### PR TITLE
Parser for "Transport for London"

### PR DESCRIPTION
**Pull request by balcy**
- add Transport For London (TFL) parser
- add color support for route parts, currently only used for TFL on Ubuntu touch, ignored for other backends and devices.

### CODE REVIEW

**Comment by Thaodan** [comment]
Can you clean that PR up? It contains my other commits not relating to this.

**Comment by balcy** [comment]
would it be OK to rebase it after the following PRs are merged ?
https://github.com/smurfy/fahrplan/pull/201
https://github.com/smurfy/fahrplan/pull/244

**Comment by Thaodan** [comment]
I'm not the one to decide that but its easier to merge and this pr looks very dirty.

**Comment by balcy** [comment]
Ok let's keep it on hold for now.
[edit: I did not create a feature branch back then, and rebased it it to the ownership and rmv PR. But you cannot add new parsers indepedently anyway]

**Comment by balcy** [comment]
Another possibility would be merging https://github.com/smurfy/fahrplan/pull/269 instead. That contains the currently released and tested fahrplan version on the Open Store for ubuntu touch. That already does contain this PR.

**Pull request closed without merging**
