### PR TITLE
Rename title and button for dialog (Copyright -> License)

### PR DESCRIPTION
**Pull request by bittner**
As discussed on [Transifex](https://www.transifex.com/leppa/fahrplan/translate/#de/en/41276321), these are the changes to the source code. Untested, but should be okay: I was careful.

After merging the changed resources need to be pushed to Transifex and translated again.

**NOTE:** Line endings are CR/LF (Windows), I left them as they are. Not sure whether converting all sources to Unix line endings wouldn't be better.

### CODE REVIEW

**Comment by bittner** [comment]
@smurfy @leppa Would you mind merging the changes for translation?

**Comment by smurfy** [comment]
nope :D

**Comment by leppa** [comment]
I just pushed the updated translation source to Transifex

**Comment by smurfy** [comment]
thanks

**Pull request merged**
