### PR TITLE
Ubuntu: Add word wrapping for labels on JourneyDetailsResultsPage

### PR DESCRIPTION
**Pull request by nikwen**
As requested by @leppa

### CODE REVIEW

**Comment by leppa** [comment]
Thank you, @nikwen.

@mzanetti, can you test it?

**Comment by mzanetti** [comment]
tested, works.

Thanks Niklas!

**Comment by mzanetti** [comment]
@smurfy good to go

**Comment by nikwen** [comment]
You're welcome. And thanks for merging. :)

**Pull request merged**
