### PR TITLE
[ubuntu] restore window geometry on ubuntu desktop

### PR DESCRIPTION
**Pull request by benni0815**

### CODE REVIEW

**Comment by smurfy** [comment]
does it make sense to use this on all platforms?`

**Comment by benni0815** [comment]
I don't think that any other touch UI cares about window geometry. Most of them even use ```view->showFullScreen()```. But actually I don't know.

For the desktop-test you could use this approach (if you want that):
http://doc.qt.digia.com/4.6/restoring-geometry.html

**Comment by mzanetti** [comment]
Works for me.

**Comment by mzanetti** [comment]
Oh wait. I just saw the code now. Only tested it so far.

I see that you're setting the fahrplan2.svg icon. I'm not ok with that. Ubuntu uses a shader on all icons to cut out the squircle shape. Looks really odd if that's done on the harmattan-style squircle. Please only use the fahrplan2_square icons for Ubuntu.

**Comment by mzanetti** [comment]
An now I just that the qrc file maps "fahrplan2.svg" to "fahrplan2-square.svg". So all fine again.

(I shouldn't do code reviews before having breakfast :)  - Sorry for the noise)

**Comment by smurfy** [comment]
hehe, need a coffee soon too :)

I also planned the next release for today.

**Pull request merged**
