### PR TITLE
Use Ubuntu.Components 1.3 features

### PR DESCRIPTION
**Pull request by krnekhelesh**
Ubuntu.Components 1.3 brings a host of new components that help with list item performance and more adaptable page headers. This pull request implements the following,
- Migrated CustomListItem to **ListItemLayout**
- Switch JourneyResultsPage over to **ListItemLayout**
- Replaced fontSize with **textSize** property introduced in UC 1.3 (_fontSize used string comparison which was expensive_)
- Migrated to **PageHeaders** which is a lot more customizable and a prerequisite for using AdaptivePageLayouts.

### CODE REVIEW

**Comment by krnekhelesh** [comment]
@mzanetti Please review and merge when you have time.

**Comment by mzanetti** [comment]
Sorry it took so long... But here goes the review:

Code looks fine. Thanks a lot for that!

Testing it I found 2 small issues. Both not introduced by this branch, but made visible through it:

* The about page doesn't fit any more on screen (testing on a Nexus 4). There's a Column in there with no height set (using the childrenRect.height). I guess the contents should be scaled accordingly to the available screen space.

* The 2 popups in the MainPage (backend selection and train types selection have color palette issues. There's a hack in the code which was required in the early days but now it actually breaks the colors. Please just delete those few lines and it should be ok.

**Comment by krnekhelesh** [comment]
Thanks for the review. Fixed the 2 issues that you listed.

**Comment by mzanetti** [comment]
thanks. lgtm now.

**Comment by smurfy** [comment]
Ok i will merge this changes soon.

**Pull request merged**
